config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'posts#index'

  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, :author, :short_text, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
         redirect_to @post, notice: 'Post created' 
    else 
         render ‘new’
    end 
  end

  def edit
  end

  def update
    if @post.update(post_params)
         redirect_to @post, notice: 'Update successful'
    else
         render ‘edit’
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Post destroyed' 
  end

  private

  def post_params
      params.require(:post).permit(:title, :content, :author, :short_text, :image)
  end

  def find_post
      @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<body>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Magazine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to '/' do %>
          <%= image_tag 'https://s3.amazonaws.com/magazine.demo/wordmark.png' , class: 'navbar__logo'%>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>

        <ul class="nav navbar-nav navbar-right">
        <%= link_to 'New Post', '/posts/new', class: 'navbar-newpost' %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    </nav>

  </head>

    <main>
      <div class="row" id="blog">

        <%= yield %>
        
      </div>
    </main>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  
  <%= f.label :image %><br>
    <%= f.file_field :image %><br>

    <%= f.label :title %><br>
    <%= f.text_area :title, placeholder: 'Post title here', class: "newpost__textarea"%><br>

    <%= f.label :author %><br>
    <%= f.text_area :author, placeholder: 'Author name here', class: "newpost__textarea" %><br>

    <%= f.label :short_text %><br>
    <%= f.text_area :short_text, placeholder: 'Short text here', class: "newpost__textarea" %><br>

    <%= f.label :content %><br>
    <%= f.text_area :content, placeholder: 'Post text here', class: "newpost__content"%><br>

    <%= f.submit class: "newpost__create"%>
  </h1>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="blog__header">
  <h6 class="blog__brand">FINTROS</h6>
  <h1>Magazine</h1>
  <h6 class="blog__subheader">Strategies And Stories To Help You In Your Job Search</h6>
</div>

<div class="columns">


  <% @posts.each do |post| %>
    <div class="grid-item" %>
      <div class="blog__card">
        <div class="card-block">
        <%= link_to post do %>
          <% if post.image %>
            <%= image_tag post.image.to_s, class: 'img-responsive' %>
          <% end %>
        <% end %>
        <div class="blog__card__text">
        <h1 class="blog__card__title"><%= link_to post.title, post %></h1>
        <%= post.short_text %>
        </div>
        </div>
      </div>
    </div>

  <% end %>

  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<article class='post'> 
<div class='post__text'>
  <%= image_tag @post.image.to_s, class: 'img-responsive' %>

  <h1><%= @post.title %></h1>
  <h2><%= @post.author %></h2>
  <p><%= simple_format @post.content %></p>

  <div class='post__button'>
    <%= link_to 'Edit', edit_post_path(@post) , class:'navbar-newpost pull-left'%>
    <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Do you wanna delete this post?' } , class:'navbar-newpost pull-right'%>
  </div>
</div>
</article>